### ISSUE TITLE
Broken Financial Track Test

### ISSUE THREAD

**Issue by jawalonoski** [fhir-crucible/plan_executor#109]
https://projectcrucible.org/servers/5543e1e16d6d319467000000#58786cec637275591f0c0000/connectathonfinancialtracktest/C9F_1A

**Comment by jawalonoski** [comment]
```
NoMethodError: undefined method `preauth_claim' for #<Crucible::Generator::Resources:0x007fc8ceae82f8>
/Users/jwalonoski/git/plan_executor/lib/tests/suites/connectathon_financial_track.rb:31:in `setup'
/Users/jwalonoski/git/plan_executor/lib/tests/base_test.rb:53:in `execute_test_methods'
/Users/jwalonoski/git/plan_executor/lib/tests/base_test.rb:43:in `execute'
/Users/jwalonoski/git/plan_executor/lib/executor.rb:13:in `execute'
lib/tasks/tasks.rake:138:in `execute_test'
```
