### ISSUE TITLE
Fatal Error: undefined method `client=' for nil:NilClass

### ISSUE THREAD

**Issue by rickysahu** [fhir-crucible/plan_executor#133]
I pulled the most recent updates on master, when through bundle install and ran the tests and started seeing errors that I wasnt getting before. 
**`Fatal Error: undefined method `client=' for nil:NilClass`**

Previously, these tests were passing fine on 962a643.

Here's some of the output from `bundle exec rake crucible:execute[http://localhost:6006/test_stu3dev,ResourceTest,Patient]`

I'd love any suggestions on a dependency or something else I may be missing.

```
ResourceTest_Patient
      PASS x000_read_type_test: 
     ERROR x010_create_new_test: Fatal Error: undefined method `client=' for nil:NilClass
            ----------------------------------------
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bundler/gems/fhir_client-79229522dcee/lib/fhir_client/sections/crud.rb:168:in `base_create'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bundler/gems/fhir_client-79229522dcee/lib/fhir_client/sections/crud.rb:123:in `create'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bundler/gems/fhir_client-79229522dcee/lib/fhir_client/ext/model.rb:73:in `create'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/suites/resource_test.rb:95:in `block (2 levels) in <class:ResourceTest>'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/base_test.rb:136:in `ignore_client_exception'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/suites/resource_test.rb:95:in `block in <class:ResourceTest>'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/suites/base_suite.rb:78:in `instance_eval'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/suites/base_suite.rb:78:in `block in test'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/base_test.rb:89:in `call'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/base_test.rb:89:in `execute_test_method'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/base_test.rb:74:in `block in execute_test_methods'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/base_test.rb:70:in `each'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/base_test.rb:70:in `execute_test_methods'
            /Users/rickysahu/Desktop/git/plan_executor/lib/tests/suites/resource_test.rb:25:in `execute'
            lib/tasks/tasks.rake:136:in `execute_test'
            lib/tasks/tasks.rake:98:in `block (3 levels) in <top (required)>'
            /Users/rickysahu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
            lib/tasks/tasks.rake:94:in `block (2 levels) in <top (required)>'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
            /Users/rickysahu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
            ----------------------------------------
     ERROR x012_conditional_create_(no_matches)_test: Fatal Error: undefined method `client=' for nil:NilClass
            ----------------------------------------
            /Users/rickysahu/.rvm/gems/ruby-2.3.3/bundler/gems/fhir_client-79229522dcee/lib/fhir_client/sections/crud.rb:168:in `base_create'

```

**Comment by arscan** [comment]
Thanks for letting us know about this issue @rickysahu.  Looks like this update is the culprit:

https://github.com/fhir-crucible/fhir_client/compare/ead75da567a832023d72038f5c0e4ae2d4526fbd...master#diff-e9b54aa865628d53a03cf241da314036L150

Is there any chance that you could capture your server's response body and headers on this request?  My guess is that our client thinks that your server is returning a resource in the body because of the content type being returned, but we can't parse it as a resource and it ends up as nil.

**Comment by rickysahu** [comment]
Yeah that may be the problem. im not sending any headers. and the body is just some debugging content i had currently. 

no headers sent
body 
```
{ id: '4ed6584bc493',
  version: '0',
  meta: 
   { tag: [ [Object], [Object] ],
     versionId: '0',
     lastUpdated: 2017-06-08T11:41:57.074Z } }
```

im guessing i need to add the Content-Type: application/fhir+json header?

**Comment by arscan** [comment]
Hmm, if you don't send the Content-Type header, create should just parrot back the resource that was POSTed, which should be a valid resource (and not nil, which is what is causing this to break).

**Comment by rickysahu** [comment]
The issue was that the resource I was sending back was not 100% conformant. I was actually providing the correct json header. The error just threw me off since the only change i made bw tests was updating crucible, but its good that the tests check the response more specifically now. Thanks for helping me look at this.

**Comment by arscan** [comment]
Great, glad we got that sorted out.   I may consider reworking some of this code so that it doesn't throw such a hard error, but instead fails the test saying something like 'invalid resource returned.'  But as long as you return valid resources this shouldn't be a problem.  Thanks.
